### PR TITLE
handle multiline input

### LINKED ISSUE #1483: tcp input + multiline codec won't work correctly with huge ingress traffic
the tcp input and the multiline codec interact really badly resulting in dropped and truncated messages.

the tcp input reads from a socket via socket.sysread(16384) this just reads the maximum data available on the socket. It does not read single lines.
 - the multiline codec will fail hardly as it assumes it only has to decode single complete lines
 - the default line codec is working correctly

easy to test just push more than one line to the tcp input which can be read in a single sysread call and use a multiline filter
  ``nc localhost 9001 < biglogfile.log #netcat does this very reliable for me (ubuntu 12.04)``

i do not know what the interface definition is but i think the multiline codec needs fixing. Probably by just using the line codec followed by the multiline codec. But this composition cannot be done via configuration.

### PR DESCRIPTION
**Pull request by jsvd**
splits incoming messages by new line and processes each sequentially.

Fixes https://github.com/elasticsearch/logstash/issues/1483

### CODE REVIEW

**Comment by suyograo** [comment]
@jsvd is this ok to merge or should we use the `line codec` to split lines?

**Comment by jsvd** [comment]
I don't think it makes sense to use the line codec here.

The `decode` method receives the multiline string, splits it and uses each line individually.
Using the codec would mean that each line would be wrapped in a LogStash::Event only to be unwrapped again through `event["message"]`

**Comment by suyograo** [comment]
ok, make sense

**Comment by suyograo** [comment]
LGTM, merging

**Pull request closed without merging**
